MDTopAppBar:
    title: "MDTopAppBar"
    left_action_items: [["menu", lambda x: app.callback()]]
    
    right_action_items:
        [
        ["home", lambda x: app.callback(x), "Home"],
        ["message-star", lambda x: app.callback(x), "Message star"],
        ["message-question", lambda x: app.callback(x), "Message question"],
        ["message-reply", lambda x: app.callback(x), "Message reply"],
        ]

MDBottomAppBar:

    MDTopAppBar:
        title: "Title"
        icon: "git"
        type: "bottom"
        left_action_items: [["menu", lambda x: x]]
        on_action_button: app.callback(self.icon)